-- 코드를 입력하세요
SELECT c.CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR AS c
        INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h ON c.CAR_ID = h.CAR_ID
        WHERE c.CAR_TYPE = '세단' AND h.START_DATE LIKE '_____10%'
        GROUP BY c.CAR_ID
        ORDER BY 1 DESC;
        